### ISSUE TITLE
Mauvais test, il faut tester si la liste n'est pas vide

### ISSUE THREAD

**Issue by Idricealy** [Jean2B/univ#1]
https://github.com/Jean2B/univ/blob/01b2ac6c2f164e4172f255e2447600ce6cb5d72a/L3%20Info/Atelier3.py#L82

**Comment by Jean2B** [comment]
Corrigé
https://github.com/Jean2B/univ/blob/e28a0af485c6df9ca6575169bacce23f977523df/L3%20Info/Atelier3.py#L84
